### ISSUE TITLE
Editing Access

### ISSUE THREAD

**Issue by EricArcher** [SIO-BUG/BUG-Resources#1]
Jessica/Tess,

Can you add Lisa and I (and others) as collaborators so we can edit the Wiki?
My GitHub ID is [EricArcher](https://github.com/EricArcher)

**Comment by bluegenes** [comment]
Hi Eric,

You should now have write access -- let me know if there are any issues.

thanks!

Tess

On Sat, Jan 23, 2016 at 10:38 AM, Eric Archer notifications@github.com
wrote:

> Jessica/Tess,
> 
> Can you add Lisa and I (and others) as collaborators so we can edit the
> Wiki?
> My GitHub ID is EricArcher https://github.com/EricArcher
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SIO-BUG/BUG-Resources/issues/1.

## 

Nuri Teresa Pierce
PhD Candidate, Marine Biology
NSF GRFP and IGERT Fellow
Scripps Institution of Oceanography, UCSD
(619) 729-1964
ntpierce@ucsd.edu

**Comment by EricArcher** [comment]
Looks good. Thanks! I'll get started filling out some bits next week.
